inherit_from:
  - ./rubocop/config/base.yml
  - ./rubocop/config/rails.yml
  - ./rubocop/config/rspec.yml # RSpec 利用時のみ
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - bin/**/*
    - config/*
    - config/environments/*
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
