inherit_gem:
  rubocop-config-timedia:
    - config/base.yml
    - config/rails.yml
    - config/rspec.yml # RSpec 利用時のみ
inherit_from:
  # - ./rubocop/config/base.yml
  # - ./rubocop/config/rails.yml
  # - ./rubocop/config/rspec.yml # RSpec 利用時のみ
  - .rubocop_todo.yml
AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - bin/**/*
    - config/*
    - config/environments/*
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*
