openapi: 3.0.3
info:
  title: チュートリアル用API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
tags:
  - name: token
    description: アクセストークンに関するAPI
paths:
  /token:
    post:
      tags:
        - token
      summary: ベアラートークンを生成する
      operationId: createToken
      requestBody:
        required: true
        description: ユーザのemailとpassword
        content:
          application/json:
            schema:
              required:
                - email
                - password
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                  minLength: 6
      responses:
        '200':
          description: 成功した場合
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
                    example: AAAAAAAAAAAAAAAAAAAAAMLheAAAAAAA0%2BuSeid%2BULvsea4JtiGRiSDSJSI%3DEUifiRBkKG5E2XzMDjRfl76ZC9Ub0wnz4XsNiRVBChTYbJcE3F

        '401':
          description: 入力を間違えて失敗した場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: エラーのタイプ
                          example: access_token
                        message:
                          type: string
                          description: エラーのメッセージ
                          example: Incorrect email or password

        '403':
          description: ユーザに権限がなくて失敗した場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: エラーのタイプ
                          example: access_token
                        message:
                          type: string
                          description: エラーのメッセージ
                          example: You are not admin user
  /users:
    post:
      security:
        - bearerAuth: []
      tags:
        - users
      summary: ユーザを作成する
      operationId: createUser
      requestBody:
        description: アクセストークンを返す
        content:
          application/json:
            schema:
              required:
                - name
                - email
                - password
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                  minLength: 6
                admin:
                  type: boolean

      responses:
        '200':
          description: 成功した場合
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  email:
                    type: string
                    format: email
                  admin:
                    type: boolean
                  activated:
                    type: boolean
                  activated_at:
                    type: string
                    nullable: true
                    format: date-time
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time

        '400':
          description: パラメータの形式が間違っていた場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      example:
                        - name: email
                          message: is invalid
                        - name: name
                          message: Can't be blank
                        - name: name
                          message: is too short (minimum is 0 characters)
        '401':
          description: アクセストークンが無効な場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      example:
                        - name: access_token
                          message: Unauthorized. Invalid token

        '404':
          description: 存在しないIDを指定した場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      example:
                        - name: user_id
                          message: User does not exist
        '422':
          description: ユーザが既に存在している場合
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      example:
                        - name: email
                          message: has already been taken

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
