version: '3'

services:
  app:
    container_name: tutorial-app
    build:
      context: .
      dockerfile: ./app/Dockerfile
      args:
        VARIANT: '3.2-bullseye'
        BUNDLER_VERSION: '2.4.10'
        RAILS_VERSIONS: '7.0.4'
        NODE_VERSION: '18'
    volumes:
      - ..:/app:delegated
      - bundle-volume:/usr/local/bundle
      - public:/app/public
      - tmp:/app/tmp
    tty: true

  web:
    container_name: tutorial-web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - public:/app/public
      - tmp:/app/tmp
    ports:
      - '80:80'
    depends_on:
      - app

volumes:
  bundle-volume:
  public:
  tmp:
