name: Run rspec

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: insert key
        run: echo -e ${{ secrets.RAILS_MASTER_KEY }} > config/master.key
      - name: Check rspec
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            rails db:reset RAILS_ENV=development
            rails db:migrate RAILS_ENV=development
            rails s &
            sleep 10
            bundle exec rails assets:precompile
            bundle exec rspec
