name: Run rspec

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Check rspec
        uses: devcontainers/ci@v0.3
        with:
          runCmd: bundle exec rspec
